# Generated by Django 5.1.3 on 2024-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Trainer', 'Trainer'), ('Wellness Organization', 'Wellness Organization')], default='Student', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='No bio provided.'),
        ),
    ]
