# Generated by Django 5.1.3 on 2024-12-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='This is test'),
            preserve_default=False,
        ),
    ]
