# Generated by Django 5.1.3 on 2024-12-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_role_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
