# Generated by Django 5.1.3 on 2024-12-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_id'),
        ('base', '0004_remove_profile_role'),
    ]

    operations = [
    ]
