# Generated by Django 5.1.3 on 2024-12-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_bio'),
        ('base', '0005_merge_0002_alter_user_id_0004_remove_profile_role'),
    ]

    operations = [
    ]
